FROM alpine

RUN apk update && apk add python3 py3-pip libffi-dev gcc make python3-dev musl-dev openssl-dev
RUN pip3 install -U pip setuptools
RUN pip3 install -U wheel
RUN pip3 install -U django redis celery pwntools

# Nicer dev stuff
RUN pip3 install -U ipython watchdog pyyaml

COPY . /app
WORKDIR /app

RUN ./manage.py migrate
CMD ./manage.py runserver 0.0.0.0:80
